/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-07-11 22:30:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.swing.JOptionPane;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Luis%20R/Desktop/PIT-Ansa/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/ProyectoAnsa/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar!/META-INF/struts-jquery-tags.tld", Long.valueOf(1389659760000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.20.jar", Long.valueOf(1459392378000L));
    _jspx_dependants.put("jar:file:/C:/Users/Luis%20R/Desktop/PIT-Ansa/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/ProyectoAnsa/WEB-INF/lib/struts2-core-2.3.20.jar!/META-INF/struts-tags.tld", Long.valueOf(1416622474000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar", Long.valueOf(1466699613024L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.swing.JOptionPane");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fhead_0026_005fjqueryui_005fjquerytheme_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fa_0026_005fopenDialog_005feffect_005fbuttonIcon_005fbutton;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fname_005flabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpassword_0026_005fname_005flabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fsubmit_0026_005fvalue_005fbutton_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionerror_0026_005fcssStyle_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsj_005fhead_0026_005fjqueryui_005fjquerytheme_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsj_005fa_0026_005fopenDialog_005feffect_005fbuttonIcon_005fbutton = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fname_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fname_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsj_005fsubmit_0026_005fvalue_005fbutton_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionerror_0026_005fcssStyle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsj_005fhead_0026_005fjqueryui_005fjquerytheme_005fnobody.release();
    _005fjspx_005ftagPool_005fsj_005fa_0026_005fopenDialog_005feffect_005fbuttonIcon_005fbutton.release();
    _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.release();
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fname_005flabel_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fname_005flabel_005fnobody.release();
    _005fjspx_005ftagPool_005fsj_005fsubmit_0026_005fvalue_005fbutton_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005factionerror_0026_005fcssStyle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/jpeg\" href=\"imagenes/rodr-saav.jpeg\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/estilos.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/******************************************\r\n");
      out.write("* Snow Effect Script- By Altan d.o.o. (http://www.altan.hr/snow/index.html)\r\n");
      out.write("* Visit Dynamic Drive DHTML code library (http://www.dynamicdrive.com/) for full source code\r\n");
      out.write("* Last updated Nov 9th, 05' by DD. This notice must stay intact for use\r\n");
      out.write("******************************************/\r\n");
      out.write("  function openwindow(){\r\n");
      out.write("window.open(\"autumn_effect.htm\",\"\",\"width=350,height=500\")\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  //Configure below to change URL path to the snow image\r\n");
      out.write("  var snowsrc=\"snow.gif\"\r\n");
      out.write("  // Configure below to change number of snow to render\r\n");
      out.write("  var no = 20;\r\n");
      out.write("  // Configure whether snow should disappear after x seconds (0=never):\r\n");
      out.write("  var hidesnowtime = 0;\r\n");
      out.write("  // Configure how much snow should drop down before fading (\"windowheight\" or \"pageheight\")\r\n");
      out.write("  var snowdistance = \"pageheight\";\r\n");
      out.write("\r\n");
      out.write("///////////Stop Config//////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("  var ie4up = (document.all) ? 1 : 0;\r\n");
      out.write("  var ns6up = (document.getElementById&&!document.all) ? 1 : 0;\r\n");
      out.write("\r\n");
      out.write("\tfunction iecompattest(){\r\n");
      out.write("\treturn (document.compatMode && document.compatMode!=\"BackCompat\")? document.documentElement : document.body\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  var dx, xp, yp;    // coordinate and position variables\r\n");
      out.write("  var am, stx, sty;  // amplitude and step variables\r\n");
      out.write("  var i, doc_width = 800, doc_height = 600; \r\n");
      out.write("  \r\n");
      out.write("  if (ns6up) {\r\n");
      out.write("    doc_width = self.innerWidth;\r\n");
      out.write("    doc_height = self.innerHeight;\r\n");
      out.write("  } else if (ie4up) {\r\n");
      out.write("    doc_width = iecompattest().clientWidth;\r\n");
      out.write("    doc_height = iecompattest().clientHeight;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  dx = new Array();\r\n");
      out.write("  xp = new Array();\r\n");
      out.write("  yp = new Array();\r\n");
      out.write("  am = new Array();\r\n");
      out.write("  stx = new Array();\r\n");
      out.write("  sty = new Array();\r\n");
      out.write("  snowsrc=(snowsrc.indexOf(\"\")!=-1)? \"snow.gif\" : snowsrc\r\n");
      out.write("  for (i = 0; i < no; ++ i) {  \r\n");
      out.write("    dx[i] = 0;                        // set coordinate variables\r\n");
      out.write("    xp[i] = Math.random()*(doc_width-50);  // set position variables\r\n");
      out.write("    yp[i] = Math.random()*doc_height;\r\n");
      out.write("    am[i] = Math.random()*50;         // set amplitude variables\r\n");
      out.write("    stx[i] = 0.02 + Math.random()/50; // set step variables\r\n");
      out.write("    sty[i] = 0.7 + Math.random();     // set step variables\r\n");
      out.write("\t\tif (ie4up||ns6up) {\r\n");
      out.write("      if (i == 0) {\r\n");
      out.write("        document.write(\"<div id=\\\"dot\"+ i +\"\\\" style=\\\"POSITION: absolute; Z-INDEX: \"+ i +\"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\\\"><a href=\\\"http://dynamicdrive.com\\\"><img src='\"+snowsrc+\"' border=\\\"0\\\"><\\/a><\\/div>\");\r\n");
      out.write("      } else {\r\n");
      out.write("        document.write(\"<div id=\\\"dot\"+ i +\"\\\" style=\\\"POSITION: absolute; Z-INDEX: \"+ i +\"; VISIBILITY: visible; TOP: 15px; LEFT: 15px;\\\"><img src='\"+snowsrc+\"' border=\\\"0\\\"><\\/div>\");\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function snowIE_NS6() {  // IE and NS6 main animation function\r\n");
      out.write("    doc_width = ns6up?window.innerWidth-10 : iecompattest().clientWidth-20;\r\n");
      out.write("\t\tdoc_height=(window.innerHeight && snowdistance==\"windowheight\")? window.innerHeight : (ie4up && snowdistance==\"windowheight\")?  iecompattest().clientHeight : (ie4up && !window.opera && snowdistance==\"pageheight\")? iecompattest().scrollHeight : iecompattest().offsetHeight;\r\n");
      out.write("\tif (snowdistance==\"windowheight\"){\r\n");
      out.write("\t\tdoc_height = window.innerHeight || iecompattest().clientHeight\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tdoc_height = iecompattest().scrollHeight\r\n");
      out.write("\t}\r\n");
      out.write("    for (i = 0; i < no; ++ i) {  // iterate for every dot\r\n");
      out.write("      yp[i] += sty[i];\r\n");
      out.write("      if (yp[i] > doc_height-50) {\r\n");
      out.write("        xp[i] = Math.random()*(doc_width-am[i]-30);\r\n");
      out.write("        yp[i] = 0;\r\n");
      out.write("        stx[i] = 0.02 + Math.random()/20;\r\n");
      out.write("        sty[i] = 0.7 + Math.random();\r\n");
      out.write("      }\r\n");
      out.write("      dx[i] += stx[i];\r\n");
      out.write("      document.getElementById(\"dot\"+i).style.top=yp[i]+\"px\";\r\n");
      out.write("      document.getElementById(\"dot\"+i).style.left=xp[i] + am[i]*Math.sin(dx[i])+\"px\";  \r\n");
      out.write("    }\r\n");
      out.write("    snowtimer=setTimeout(\"snowIE_NS6()\", 10);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\tfunction hidesnow(){\r\n");
      out.write("\t\tif (window.snowtimer) clearTimeout(snowtimer)\r\n");
      out.write("\t\tfor (i=0; i<no; i++) document.getElementById(\"dot\"+i).style.visibility=\"hidden\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("if (ie4up||ns6up){\r\n");
      out.write("    snowIE_NS6();\r\n");
      out.write("\t\tif (hidesnowtime>0)\r\n");
      out.write("\t\tsetTimeout(\"hidesnow()\", hidesnowtime*1000)\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("/* valores genericos para los copos */\r\n");
      out.write(".copo {\r\n");
      out.write("\tbackground-color: #00f;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 0;\r\n");
      out.write("}\r\n");
      out.write("/* definimos los 4 tipos de copos */\r\n");
      out.write(".copo1 {\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".copo2 {\r\n");
      out.write("\theight: 2px;\r\n");
      out.write("\twidth: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".copo3 {\r\n");
      out.write("\theight: 3px;\r\n");
      out.write("\twidth: 3px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".copo4 {\r\n");
      out.write("\theight: 4px;\r\n");
      out.write("\twidth: 4px;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("        var anchuraMax=0;\r\n");
      out.write("        var alturaMax=0;\r\n");
      out.write("        var copos=new Array;\r\n");
      out.write(" \r\n");
      out.write("        /**\r\n");
      out.write("         * Funcion inicial\r\n");
      out.write("         * Tiene que recibir:\r\n");
      out.write("         *  numeroCopos a mostrar\r\n");
      out.write("         *  anchura y altura por donde aparecen los copos\r\n");
      out.write("         *  velocidad de movimiento de los mismos\r\n");
      out.write("         */\r\n");
      out.write("        function inicializar(numeroCopos, anchura, altura, velocidad)\r\n");
      out.write("        {\r\n");
      out.write("            var i, x, y;\r\n");
      out.write("            copos = new Array(numeroCopos);\r\n");
      out.write("            for (i = 0; i<numeroCopos; i++)\r\n");
      out.write("            {\r\n");
      out.write("                x = parseInt(Math.random()*anchura);\r\n");
      out.write("                y = parseInt(Math.random()*altura);\r\n");
      out.write("                dibujaCopo(i,x,y);\r\n");
      out.write("                copos[i] = document.getElementById(\"c\"+i);\r\n");
      out.write("            }\r\n");
      out.write("            alturaMax = altura;\r\n");
      out.write("            anchuraMax = anchura;\r\n");
      out.write("            setInterval(nevar, velocidad);\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        // Función inicial que dibuja los copos en la pantalla\r\n");
      out.write("        function dibujaCopo(numeroCopo, x, y)\r\n");
      out.write("        {\r\n");
      out.write("            var tamano = Math.floor(Math.random()*4)+1;\r\n");
      out.write("            document.write('<div id=\"c'+numeroCopo+'\" class=\"copo copo'+tamano+'\" style=\"left:'+x+'px; top:'+y+'px;\"></div>');\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        // Función que controla el movimiento de los copos por la pantalla\r\n");
      out.write("        function nevar()\r\n");
      out.write("        {\r\n");
      out.write("            var i, x, y;\r\n");
      out.write("            for (i = 0; i < copos.length; i++)\r\n");
      out.write("            {\r\n");
      out.write("                // cogemos las posiciones de cada elemento\r\n");
      out.write("                y = parseInt(copos[i].style.top);\r\n");
      out.write("                x = parseInt(copos[i].style.left);\r\n");
      out.write(" \r\n");
      out.write("                y+=Math.floor(Math.random()*4)+1;\r\n");
      out.write("                copos[i].style.top = y;\r\n");
      out.write(" \r\n");
      out.write("                // si ha llegado al final de la pantalla\r\n");
      out.write("                if(y>document.body.scrollTop+alturaMax)\r\n");
      out.write("                {\r\n");
      out.write("                    // posicionamos nuevamente en la parte superior\r\n");
      out.write("                    copos[i].style.top = document.body.scrollTop-(Math.round(Math.random()*10)+1);\r\n");
      out.write("                    // cogemos una posicion horizontal aleatoria\r\n");
      out.write("                    copos[i].style.left=parseInt((Math.random()*anchuraMax)+1);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      if (_jspx_meth_sj_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Bienvenido Al Sistema Ansa</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"imagenes/f.jpg\"\r\n");
      out.write("\tstyle=\"background-repeat: no-repeat; background-position: center\"\r\n");
      out.write("\tbgproperties=\"fixed\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"image\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img src=\"imagenes/mision.jpg\" alt=\"Ansa SAC\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<p align=\"center\">\r\n");
      out.write("\t\t<u><EM><font size=\"10\">Empresa Textil: Ansa </font></em></u>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<p align=\"center\">\r\n");
      out.write("\t\t<TT>\r\n");
      out.write("\t\t\t<font size=\"4\"> Lorem ipsum dolor sit amet, consectetuer\r\n");
      out.write("\t\t\t\tadipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum\r\n");
      out.write("\t\t\t\tsociis natoque penatibus et magnis dis parturient montes, nascetur\r\n");
      out.write("\t\t\t\tridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,\r\n");
      out.write("\t\t\t\tpretium quis, sem. Nulla consequat massa quis enim. Donec pede\r\n");
      out.write("\t\t\t\tjusto, fringilla vel, aliquet nec, vulputate eget, arcu. In enim\r\n");
      out.write("\t\t\t\tjusto, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam\r\n");
      out.write("\t\t\t\tdictum felis eu pede mollis pretium. Integer tincidunt. Cras\r\n");
      out.write("\t\t\t\tdapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend\r\n");
      out.write("\t\t\t\ttellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend\r\n");
      out.write("\t\t\t\tac, enim. </font>\r\n");
      out.write("\t\t</tt>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<center>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_sj_005fa_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_sj_005fdialog_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\t");
      if (_jspx_meth_sj_005fdialog_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_s_005factionerror_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("inicializar(40, 1300, 50, 300, 300, 800);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sj_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:head
    com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag _jspx_th_sj_005fhead_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fsj_005fhead_0026_005fjqueryui_005fjquerytheme_005fnobody.get(com.jgeppert.struts2.jquery.views.jsp.ui.HeadTag.class);
    _jspx_th_sj_005fhead_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fhead_005f0.setParent(null);
    // /index.jsp(207,0) name = jqueryui type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fhead_005f0.setJqueryui("true");
    // /index.jsp(207,0) name = jquerytheme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fhead_005f0.setJquerytheme("trontastic");
    int _jspx_eval_sj_005fhead_005f0 = _jspx_th_sj_005fhead_005f0.doStartTag();
    if (_jspx_th_sj_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fhead_0026_005fjqueryui_005fjquerytheme_005fnobody.reuse(_jspx_th_sj_005fhead_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fhead_0026_005fjqueryui_005fjquerytheme_005fnobody.reuse(_jspx_th_sj_005fhead_005f0);
    return false;
  }

  private boolean _jspx_meth_sj_005fa_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:a
    com.jgeppert.struts2.jquery.views.jsp.ui.AnchorTag _jspx_th_sj_005fa_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.AnchorTag) _005fjspx_005ftagPool_005fsj_005fa_0026_005fopenDialog_005feffect_005fbuttonIcon_005fbutton.get(com.jgeppert.struts2.jquery.views.jsp.ui.AnchorTag.class);
    _jspx_th_sj_005fa_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fa_005f0.setParent(null);
    // /index.jsp(249,2) name = openDialog type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fa_005f0.setOpenDialog("Ingresar");
    // /index.jsp(249,2) name = button type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fa_005f0.setButton("true");
    // /index.jsp(249,2) name = effect type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fa_005f0.setEffect("");
    // /index.jsp(249,2) name = buttonIcon type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fa_005f0.setButtonIcon("uri-icon-newwin");
    int _jspx_eval_sj_005fa_005f0 = _jspx_th_sj_005fa_005f0.doStartTag();
    if (_jspx_eval_sj_005fa_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_sj_005fa_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_sj_005fa_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_sj_005fa_005f0.doInitBody();
      }
      do {
        out.write("Intranet");
        int evalDoAfterBody = _jspx_th_sj_005fa_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_sj_005fa_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_sj_005fa_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fa_0026_005fopenDialog_005feffect_005fbuttonIcon_005fbutton.reuse(_jspx_th_sj_005fa_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fa_0026_005fopenDialog_005feffect_005fbuttonIcon_005fbutton.reuse(_jspx_th_sj_005fa_005f0);
    return false;
  }

  private boolean _jspx_meth_sj_005fdialog_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:dialog
    com.jgeppert.struts2.jquery.views.jsp.ui.DialogTag _jspx_th_sj_005fdialog_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.DialogTag) _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.get(com.jgeppert.struts2.jquery.views.jsp.ui.DialogTag.class);
    _jspx_th_sj_005fdialog_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fdialog_005f0.setParent(null);
    // /index.jsp(251,2) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f0.setId("Ingresar");
    // /index.jsp(251,2) name = autoOpen type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f0.setAutoOpen("false");
    // /index.jsp(251,2) name = modal type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f0.setModal("true");
    // /index.jsp(251,2) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f0.setTitle("Bienvenido Al Sistema Ansa");
    // /index.jsp(251,2) name = height type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f0.setHeight("350");
    // /index.jsp(251,2) name = width type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f0.setWidth("700");
    int _jspx_eval_sj_005fdialog_005f0 = _jspx_th_sj_005fdialog_005f0.doStartTag();
    if (_jspx_eval_sj_005fdialog_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_sj_005fdialog_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_sj_005fdialog_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_sj_005fdialog_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t<br>\r\n");
        out.write("\t\t\t<center>\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_s_005fform_005f0(_jspx_th_sj_005fdialog_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t</center>\r\n");
        out.write("\t\t\t<br>\r\n");
        out.write("\t\t\t<br>\r\n");
        out.write("\t\t\t<br>\r\n");
        out.write("\t\t\t<MARQUEE BEHAVIOR=alternate> Ingrese su usuario y\r\n");
        out.write("\t\t\t\tcontraseña </MARQUEE>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_sj_005fdialog_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_sj_005fdialog_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_sj_005fdialog_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.reuse(_jspx_th_sj_005fdialog_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.reuse(_jspx_th_sj_005fdialog_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sj_005fdialog_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sj_005fdialog_005f0);
    // /index.jsp(255,4) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setAction("validaUsuarioXML");
    int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
    if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fform_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_s_005ftextfield_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_s_005fpassword_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t<label>TIpo Usuario: </label> &nbsp; &nbsp;  &nbsp;  &nbsp;\r\n");
        out.write("            <select name=\"tipou\">\r\n");
        out.write("\t\t\t\t\t\t<OPTION VALUE=\"usuario\">Usuario</OPTION>\r\n");
        out.write("\t\t\t\t\t\t<OPTION VALUE=\"administrador\">Administrador</OPTION>\r\n");
        out.write("\t\t\t\t\t</select>\r\n");
        out.write("\t\t\t\t\t<br>\r\n");
        out.write("\t\t\t\t\t<br>\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_sj_005fsubmit_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fform_0026_005faction.reuse(_jspx_th_s_005fform_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fform_0026_005faction.reuse(_jspx_th_s_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f0 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fname_005flabel_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /index.jsp(256,5) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setLabel("Usuario");
    // /index.jsp(256,5) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setName("usu");
    int _jspx_eval_s_005ftextfield_005f0 = _jspx_th_s_005ftextfield_005f0.doStartTag();
    if (_jspx_th_s_005ftextfield_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fname_005flabel_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fname_005flabel_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f0 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fname_005flabel_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /index.jsp(257,5) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setLabel("Contraseña");
    // /index.jsp(257,5) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setName("contra");
    int _jspx_eval_s_005fpassword_005f0 = _jspx_th_s_005fpassword_005f0.doStartTag();
    if (_jspx_th_s_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fname_005flabel_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fname_005flabel_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
    return false;
  }

  private boolean _jspx_meth_sj_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:submit
    com.jgeppert.struts2.jquery.views.jsp.ui.SubmitTag _jspx_th_sj_005fsubmit_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.SubmitTag) _005fjspx_005ftagPool_005fsj_005fsubmit_0026_005fvalue_005fbutton_005fnobody.get(com.jgeppert.struts2.jquery.views.jsp.ui.SubmitTag.class);
    _jspx_th_sj_005fsubmit_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /index.jsp(265,5) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fsubmit_005f0.setValue("Enviar");
    // /index.jsp(265,5) name = button type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fsubmit_005f0.setButton("true");
    int _jspx_eval_sj_005fsubmit_005f0 = _jspx_th_sj_005fsubmit_005f0.doStartTag();
    if (_jspx_th_sj_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fsubmit_0026_005fvalue_005fbutton_005fnobody.reuse(_jspx_th_sj_005fsubmit_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fsubmit_0026_005fvalue_005fbutton_005fnobody.reuse(_jspx_th_sj_005fsubmit_005f0);
    return false;
  }

  private boolean _jspx_meth_sj_005fdialog_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:dialog
    com.jgeppert.struts2.jquery.views.jsp.ui.DialogTag _jspx_th_sj_005fdialog_005f1 = (com.jgeppert.struts2.jquery.views.jsp.ui.DialogTag) _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.get(com.jgeppert.struts2.jquery.views.jsp.ui.DialogTag.class);
    _jspx_th_sj_005fdialog_005f1.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fdialog_005f1.setParent(null);
    // /index.jsp(276,1) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f1.setId("ventanaActualizacion");
    // /index.jsp(276,1) name = autoOpen type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f1.setAutoOpen("true");
    // /index.jsp(276,1) name = modal type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f1.setModal("false");
    // /index.jsp(276,1) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f1.setTitle("Sistema Ansa");
    // /index.jsp(276,1) name = height type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f1.setHeight("200");
    // /index.jsp(276,1) name = width type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdialog_005f1.setWidth("400");
    int _jspx_eval_sj_005fdialog_005f1 = _jspx_th_sj_005fdialog_005f1.doStartTag();
    if (_jspx_eval_sj_005fdialog_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_sj_005fdialog_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_sj_005fdialog_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_sj_005fdialog_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t<marquee direction=\"up\" scrolldelay=\"250\">\r\n");
        out.write("\t\t\t<hr>\r\n");
        out.write("\t\t\tBienvenido Al Sistema Ansa\r\n");
        out.write("\t\t\t<hr>\r\n");
        out.write("\t\t</marquee>\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_sj_005fdialog_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_sj_005fdialog_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_sj_005fdialog_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.reuse(_jspx_th_sj_005fdialog_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fdialog_0026_005fwidth_005ftitle_005fmodal_005fid_005fheight_005fautoOpen.reuse(_jspx_th_sj_005fdialog_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005factionerror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionerror
    org.apache.struts2.views.jsp.ui.ActionErrorTag _jspx_th_s_005factionerror_005f0 = (org.apache.struts2.views.jsp.ui.ActionErrorTag) _005fjspx_005ftagPool_005fs_005factionerror_0026_005fcssStyle_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionErrorTag.class);
    _jspx_th_s_005factionerror_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005factionerror_005f0.setParent(null);
    // /index.jsp(285,1) name = cssStyle type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005factionerror_005f0.setCssStyle("color:red;");
    int _jspx_eval_s_005factionerror_005f0 = _jspx_th_s_005factionerror_005f0.doStartTag();
    if (_jspx_th_s_005factionerror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005factionerror_0026_005fcssStyle_005fnobody.reuse(_jspx_th_s_005factionerror_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005factionerror_0026_005fcssStyle_005fnobody.reuse(_jspx_th_s_005factionerror_005f0);
    return false;
  }
}
